DROP TABLE TB_MEMBER;

CREATE TABLE TB_MEMBER (
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	AGE NUMBER NOT NULL,
	GENDER VARCHAR2(2) CHECK(GENDER IN ('M', 'F')) NOT NULL,
	LOCATION VARCHAR2(500),
	JOB VARCHAR2(300),
	TEL VARCHAR2(20),
	EMAIL VARCHAR2(100)
);

INSERT INTO TB_MEMBER
VALUES(1, '백승아', 26, 'F', '경기도 성남시', '학생', '010-1234-1234', 'abc@naver.com');

SELECT NO, NAME, AGE, GENDER, LOCATION, JOB, TEL, EMAIL
FROM TB_MEMBER;