DROP TABLE SCORE;

CREATE TABLE SCORE (
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	KOR NUMBER NOT NULL,
	ENG NUMBER NOT NULL,
	MATH NUMBER NOT NULL
);

SELECT * FROM SCORE;

INSERT INTO SCORE
VALUES(1, '¹é½Â¾Æ', 100, 100, 100);